# Generated by Django 4.1.3 on 2022-11-29 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeavePlans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.TextField(unique=True)),
                ("leave_type", models.CharField(max_length=50)),
                ("from_date", models.DateField(null=True)),
                ("to_date", models.DateField(null=True)),
                ("duration", models.CharField(max_length=50)),
                ("approval_status", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_plans",
            },
        ),
    ]
