# Generated by Django 4.1.3 on 2022-12-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_leaveplans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('login', 'Can login')]},
        ),
    ]
