# Generated by Django 4.1.3 on 2022-12-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
