# Generated by Django 4.1.3 on 2022-12-13 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_skill"),
        ("user", "0004_user_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="career_start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="current_status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="function",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="industries",
            field=models.ManyToManyField(to="common.industry"),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_skill",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_link",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="ProficiencyMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.DecimalField(decimal_places=1, max_digits=10)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proficiency_mapping",
                        to="common.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proficiency_mapping",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "proficiency_mapping",
                "unique_together": {("skill", "user")},
            },
        ),
    ]
