# Generated by Django 4.1.3 on 2023-01-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_role_alter_proficiencymapping_rating_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveplans',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaveplans',
            name='to_date',
            field=models.DateField(),
        ),
    ]
