# Generated by Django 4.1.3 on 2023-01-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career_break_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_working_day',
            field=models.DateField(null=True),
        ),
    ]
