# Generated by Django 4.1.3 on 2023-03-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_user_career_break_months_user_last_working_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile_link",
            new_name="cb_profile_link",
        ),
    ]
