# Generated by Django 4.1.3 on 2023-03-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_user_country_user_ga_profile_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
