# Generated by Django 4.1.3 on 2023-11-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_skill_updated_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('login', 'Can login'), ('search_talent', 'Can search talent'),
                                     ('view_last_working_day', 'Can view last working day')]},
        ),
    ]
