# Generated by Django 4.1.3 on 2024-03-11 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("login", "Can login"),
                    ("search_talent", "Can search talent"),
                    ("view_last_working_day", "Can view last working day"),
                    ("generate_jwt_token", "Can generate JWT token"),
                ]
            },
        ),
    ]
