export const ROLES = {
  superAdmin: "super_admin",
  admin: "admin",
  requester: "requester",
  viewer: "viewer",
  inventoryManager: "inventory_manager",
  user: "user",
};

export const SCOPES = {
  canView: "can-view",
  canCreate: "can-create",
  canUpdate: "can-update",
  canDelete: "can-delete",
  canSetClientDormant: "can-set-client-dormant",
  canAddTalent: "can-add-talent",
  canRequestTalent: "can-request-talent",
  canRemoveTalent: "can-remove-talent",
  canUpdateProjectStatus: "can-update-project-status",
  canPartiallyUpdateProjectStatus: "can-partially-update-project-status",
  canCreateRole: "can-create-role",
  canViewLWD: "can-view-lwd",
  canUpdatePeopleDetails: "can-update-people-details",
  canAccessAssets: "can-access-assets",
  canAccessUserManagement: "can-access-user-management",
  canAccessSkillPortal: "can-access-skill-portal",
  canViewNotifications: "can-view-notifications",
};

export const PERMISSIONS = {
  [ROLES.superAdmin]: [
    SCOPES.canView,
    SCOPES.canCreate,
    SCOPES.canUpdate,
    SCOPES.canDelete,
    SCOPES.canViewLWD,
    SCOPES.canUpdatePeopleDetails,
    SCOPES.canAddTalent,
    SCOPES.canRemoveTalent,
    SCOPES.canUpdateProjectStatus,
    SCOPES.canCreateRole,
    SCOPES.canSetClientDormant,
    SCOPES.canAccessAssets,
    SCOPES.canAccessSkillPortal,
    SCOPES.canViewNotifications,
    SCOPES.canAccessUserManagement,
  ],
  [ROLES.admin]: [
    SCOPES.canView,
    SCOPES.canCreate,
    SCOPES.canUpdate,
    SCOPES.canDelete,
    SCOPES.canViewLWD,
    SCOPES.canUpdatePeopleDetails,
    SCOPES.canAddTalent,
    SCOPES.canRemoveTalent,
    SCOPES.canUpdateProjectStatus,
    SCOPES.canCreateRole,
    SCOPES.canSetClientDormant,
    SCOPES.canAccessAssets,
    SCOPES.canAccessSkillPortal,
    SCOPES.canViewNotifications,
  ],
  [ROLES.requester]: [
    SCOPES.canView,
    SCOPES.canCreate,
    SCOPES.canUpdate,
    SCOPES.canDelete,
    SCOPES.canViewLWD,
    SCOPES.canRequestTalent,
    SCOPES.canPartiallyUpdateProjectStatus,
    SCOPES.canViewNotifications,
  ],
  [ROLES.viewer]: [SCOPES.canView],
  [ROLES.inventoryManager]: [SCOPES.canView, SCOPES.canViewLWD, SCOPES.canAccessAssets],
  [ROLES.user]: [],
};
