# Generated by Django 4.1.3 on 2022-12-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_client_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientpoc",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="clientpoc",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
