# Generated by Django 4.1.3 on 2023-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_clientpoc_email_alter_clientpoc_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="comment",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="clientpoc",
            name="designation",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
