# Generated by Django 4.1.3 on 2022-11-17 07:01

from django.db import migrations

from authapp.constants import RoleKeys


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name=RoleKeys.ADMIN)
    Group.objects.create(name=RoleKeys.ACCOUNT_MANAGER)


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=[RoleKeys.ADMIN, RoleKeys.ACCOUNT_MANAGER]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=delete_groups)
    ]
