# Generated by Django 4.1.3 on 2022-12-09 10:20

from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from authapp.constants import RoleKeys
from authapp.permissions import assign_permissions, revoke_permissions


def get_group_permission_map(content_type):
    group_permission_map = {
        RoleKeys.ADMIN: {
            'content_type': content_type,
            'codenames': ['add_project', 'view_project', 'change_project', 'set_privileged_project_status']
        },
        RoleKeys.ACCOUNT_MANAGER: {
            'content_type': content_type,
            'codenames': ['add_project', 'view_project', 'change_project']
        }
    }
    return group_permission_map


def assign_group_permissions(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    content_type = ContentType.objects.get_for_model(Project)
    group_permission_map = get_group_permission_map(content_type)
    assign_permissions(group_permission_map)


def revoke_group_permissions(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    content_type = ContentType.objects.get_for_model(Project)
    group_permission_map = get_group_permission_map(content_type)
    revoke_permissions(group_permission_map)


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20221201_0605'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(assign_group_permissions, reverse_code=revoke_group_permissions)
    ]
