# Generated by Django 4.1.3 on 2022-12-14 09:28

from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from authapp.constants import RoleKeys
from authapp.permissions import assign_permissions, revoke_permissions


def get_group_permission_map(content_type):
    group_permission_map = {
        RoleKeys.ADMIN: {
            'content_type': content_type,
            'codenames': ['add_projectposition', 'change_projectposition', 'delete_projectposition',
                          'view_projectposition']
        },
        RoleKeys.ACCOUNT_MANAGER: {
            'content_type': content_type,
            'codenames': ['add_projectposition', 'change_projectposition', 'delete_projectposition',
                          'view_projectposition']
        }
    }
    return group_permission_map


def assign_group_permissions(apps, schema_editor):
    ProjectPosition = apps.get_model('project', 'ProjectPosition')
    content_type = ContentType.objects.get_for_model(ProjectPosition)
    group_permission_map = get_group_permission_map(content_type)
    assign_permissions(group_permission_map)


def revoke_group_permissions(apps, schema_editor):
    ProjectPosition = apps.get_model('project', 'ProjectPosition')
    content_type = ContentType.objects.get_for_model(ProjectPosition)
    group_permission_map = get_group_permission_map(content_type)
    revoke_permissions(group_permission_map)


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20221212_0702'),
        ('project', '0002_projectposition_projectpositionskills_and_more')
    ]

    operations = [
        migrations.RunPython(assign_group_permissions, reverse_code=revoke_group_permissions)
    ]
