# Generated by Django 4.1.3 on 2023-02-14 05:31

from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from authapp.constants import RoleKeys
from authapp.permissions import assign_permissions, revoke_permissions


def get_group_permission_map(content_type):
    group_permission_map = {
        RoleKeys.ADMIN: {
            'content_type': content_type,
            'codenames': ['change_notification']
        },
        RoleKeys.ACCOUNT_MANAGER: {
            'content_type': content_type,
            'codenames': ['change_notification']
        }
    }
    return group_permission_map


def assign_group_permissions(apps, schema_editor):
    Notification = apps.get_model('project', 'Notification')
    content_type = ContentType.objects.get_for_model(Notification)
    group_permission_map = get_group_permission_map(content_type)
    assign_permissions(group_permission_map)


def revoke_group_permissions(apps, schema_editor):
    Notification = apps.get_model('project', 'Notification')
    content_type = ContentType.objects.get_for_model(Notification)
    group_permission_map = get_group_permission_map(content_type)
    revoke_permissions(group_permission_map)


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0015_auto_20230209_1059"),
        ("project", "0010_alter_project_engagement_type_notification")
    ]

    operations = [
        migrations.RunPython(assign_group_permissions, reverse_code=revoke_group_permissions)
    ]

