# Generated by Django 4.1.3 on 2023-03-14 09:28

from django.db import migrations

from authapp.constants import RoleKeys


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name=RoleKeys.USER)


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=[RoleKeys.USER]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0017_auto_20230222_1207"),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=delete_groups)
    ]
