# Generated by Django 4.1.3 on 2023-03-16 08:28

from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from authapp.constants import RoleKeys
from authapp.permissions import assign_permissions, revoke_permissions


def get_form_permission_map(content_type):
    group_permission_map = {
        RoleKeys.ADMIN: {
            'content_type': content_type,
            'codenames': ['can_change_form_related_permissions']
        }
    }
    return group_permission_map


def assign_form_related_permissions(apps, schema_editor):
    content_type = ContentType.objects.get_by_natural_key(app_label='edit_form', model='change_form_related_permissions')
    group_permission_map = get_form_permission_map(content_type)
    assign_permissions(group_permission_map)


def revoke_form_related_permissions(apps, schema_editor):
    content_type = ContentType.objects.get_by_natural_key(app_label='edit_form', model='change_form_related_permissions')
    group_permission_map = get_form_permission_map(content_type)
    revoke_permissions(group_permission_map)


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0018_auto_20230314_0928"),
        ("user", "0012_user_date_of_birth")
    ]

    operations = [
        migrations.RunPython(assign_form_related_permissions, reverse_code=revoke_form_related_permissions)
    ]