# Generated by Django 4.1.3 on 2023-03-31 12:04
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from authapp.constants import RoleKeys
from authapp.permissions import assign_permissions, revoke_permissions


def get_group_permission_map(content_type):
    group_permission_map = {
        RoleKeys.USER: {
            'content_type': content_type,
            'codenames': ['login']
        }
    }
    return group_permission_map


def assign_group_permissions(apps, schema_editor):
    User = apps.get_model('user', 'User')
    content_type = ContentType.objects.get_for_model(User)
    group_permission_map = get_group_permission_map(content_type)
    assign_permissions(group_permission_map)


def revoke_group_permissions(apps, schema_editor):
    User = apps.get_model('user', 'User')
    content_type = ContentType.objects.get_for_model(User)
    group_permission_map = get_group_permission_map(content_type)
    revoke_permissions(group_permission_map)


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0025_auto_20230325_1133"),
        ('user', '0013_user_skill_updated_time')
    ]

    operations = [
        migrations.RunPython(assign_group_permissions, reverse_code=revoke_group_permissions)

    ]
