# Generated by Django 4.1.3 on 2023-10-04 12:16

from django.db import migrations

from authapp.constants import RoleKeys

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    account_manager_group = Group.objects.get(name=RoleKeys.ACCOUNT_MANAGER)
    account_manager_group.name = RoleKeys.REQUESTER
    account_manager_group.save()
    Group.objects.create(name=RoleKeys.SUPER_ADMIN)
    Group.objects.create(name=RoleKeys.VIEWER)
    Group.objects.create(name=RoleKeys.INVENTORY_MANAGER)


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    account_manager_group = Group.objects.get(name=RoleKeys.REQUESTER)
    account_manager_group.name = RoleKeys.ACCOUNT_MANAGER
    account_manager_group.save()
    Group.objects.filter(name__in=[RoleKeys.SUPER_ADMIN, RoleKeys.VIEWER, RoleKeys.INVENTORY_MANAGER]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_auto_20230331_1204'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=delete_groups)
    ]
