# Generated by Django 4.1.3 on 2023-10-05 06:57

from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from authapp.constants import RoleKeys
from authapp.permissions import assign_permissions, revoke_permissions


def get_group_permission_map(content_type):
    group_permission_map = {
        RoleKeys.SUPER_ADMIN: {
            'content_type': content_type,
            'codenames': ['add_project', 'view_project', 'change_project', 'set_privileged_project_status']
        },
        RoleKeys.VIEWER: {
            'content_type': content_type,
            'codenames': ['view_project']
        },
        RoleKeys.INVENTORY_MANAGER: {
            'content_type': content_type,
            'codenames': ['view_project']
        }
    }
    return group_permission_map


def assign_group_permissions(apps, schema_editor):
    project = apps.get_model('project', 'Project')
    content_type = ContentType.objects.get_for_model(project)
    group_permission_map = get_group_permission_map(content_type)
    assign_permissions(group_permission_map)


def revoke_group_permissions(apps, schema_editor):
    project = apps.get_model('project', 'Project')
    content_type = ContentType.objects.get_for_model(project)
    group_permission_map = get_group_permission_map(content_type)
    revoke_permissions(group_permission_map)


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0029_client_permissions_new_groups'),
    ]

    operations = [
        migrations.RunPython(assign_group_permissions, reverse_code=revoke_group_permissions)
    ]
