# Generated by Django 4.1.3 on 2022-12-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpoc",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="projectpoc",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
