# Generated by Django 4.1.3 on 2022-12-20 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_role_alter_proficiencymapping_rating_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_skill'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilization', models.IntegerField(default=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('experience_range_start', models.IntegerField(null=True)),
                ('experience_range_end', models.IntegerField(null=True)),
                ('openings', models.IntegerField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='project.project')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.role')),
            ],
            options={
                'db_table': 'project_position',
            },
        ),
        migrations.CreateModel(
            name='ProjectPositionSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectposition')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.skill')),
            ],
            options={
                'db_table': 'project_position_skills',
            },
        ),
        migrations.AddField(
            model_name='projectposition',
            name='skills',
            field=models.ManyToManyField(through='project.ProjectPositionSkills', to='common.skill'),
        ),
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentative', models.BooleanField(default=False)),
                ('requested', models.BooleanField(default=False)),
                ('kt_period', models.IntegerField(null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='project.projectposition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_allocation',
            },
        ),
    ]
