# Generated by Django 4.1.3 on 2022-12-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_role_alter_proficiencymapping_rating_alter_user_role'),
        ('project', '0002_projectposition_projectpositionskills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectposition',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_positions', to='user.role'),
        ),
    ]
