# Generated by Django 4.1.3 on 2022-12-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_projectpoc_email_alter_projectpoc_phone_number"),
        ("project", "0003_alter_projectposition_role"),
    ]

    operations = []
