# Generated by Django 4.1.3 on 2022-12-23 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_merge_20221220_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectallocation',
            options={'permissions': [('request_add_projectallocation', 'Can request to add project allocation'), ('request_change_projectallocation', 'Can request to change project allocation')]},
        ),
        migrations.AlterUniqueTogether(
            name='projectallocation',
            unique_together={('user', 'position')},
        ),
    ]
