# Generated by Django 4.1.3 on 2022-12-26 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0005_alter_projectallocation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="account_manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_managed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
