# Generated by Django 4.1.3 on 2023-01-18 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0007_alter_projectallocation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAllocationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("utilization", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                ("kt_period", models.IntegerField(default=0)),
                ("tentative", models.BooleanField(default=False)),
                ("created_time", models.DateTimeField()),
                ("modified_time", models.DateTimeField()),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projectallocation",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_history",
                        to="project.projectposition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_allocation_history",
            },
        ),
    ]
