# Generated by Django 4.1.3 on 2023-01-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_projectallocationhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectallocationrequest",
            name="allocation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocation",
                to="project.projectallocation",
            ),
        ),
    ]
