# Generated by Django 4.1.3 on 2023-02-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_ALLOCATION", "New_Allocation"),
                    ("ALLOCATION_CHANGE", "Allocation_Change"),
                    ("NEW_ALLOCATION_REQUEST", "New_Allocation_Request"),
                    ("APPROVED_ALLOCATION_REQUEST", "Approved_Allocation_Request"),
                    ("CANCEL_ALLOCATION_REQUEST", "Cancel_Allocation_Request"),
                    ("ALLOCATION_CHANGE_REQUEST", "Allocation_Change_Request"),
                    (
                        "APPROVED_ALLOCATION_CHANGE_REQUEST",
                        "Approved_Allocation_Change_Request",
                    ),
                    (
                        "CANCEL_ALLOCATION_CHANGE_REQUEST",
                        "Cancel_Allocation_Change_Request",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
