# Generated by Django 4.1.3 on 2023-04-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="comment",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="projectpoc",
            name="designation",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
