# Generated by Django 4.1.3 on 2023-06-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_comment_projectpoc_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectposition',
            name='is_billable',
            field=models.BooleanField(default=True),
        ),
    ]
