# Generated by Django 4.1.3 on 2023-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_project_position_is_billabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpositionhistory',
            name='is_billable',
            field=models.BooleanField(default=True),
        ),
    ]
