# Generated by Django 4.1.3 on 2023-07-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InUseAsset',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('change_id', models.CharField(max_length=100)),
                ('cb_asset_id', models.TextField(null=True)),
                ('serial_num', models.TextField(null=True)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('assignee_id', models.TextField(null=True)),
                ('date_of_change', models.DateTimeField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('other_assets', models.TextField(null=True)),
                ('screenshot', models.TextField(null=True)),
                ('comments', models.TextField(null=True)),
                ('client', models.CharField(max_length=100, null=True)),
                ('project', models.CharField(max_length=100, null=True)),
                ('active', models.CharField(choices=[('INV', 'Inventory'), ('ASSI', 'Assigned'), ('TRAN', 'In Transit'), ('REP', 'In Repair')], max_length=100, null=True)),
                ('closed', models.CharField(choices=[('WR', 'Written Off'), ('NW', 'Not Working'), ('SL', 'Stolen/Lost'), ('RC', 'Returned to Client'), ('LC', 'Returned to Leasing Company')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('serial_num', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('cb_asset_id', models.CharField(max_length=100, null=True)),
                ('ownership', models.CharField(max_length=100, null=True)),
                ('screensize', models.CharField(max_length=100, null=True)),
                ('colour', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
                ('ram', models.IntegerField(null=True)),
                ('date_of_purchase', models.DateTimeField(null=True)),
                ('invoice_num', models.TextField(null=True)),
                ('link_to_invoice', models.TextField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('gst', models.IntegerField(null=True)),
                ('total_amt_paid', models.IntegerField(null=True)),
                ('vendor', models.CharField(max_length=100, null=True)),
                ('is_jump_cloud_integration', models.BooleanField(null=True)),
                ('warranty', models.IntegerField(null=True)),
                ('lease_start_date', models.DateTimeField(null=True)),
                ('leasing_company', models.CharField(max_length=100, null=True)),
                ('client_asset_allocation_date', models.DateTimeField(null=True)),
                ('active', models.CharField(choices=[('INV', 'Inventory'), ('ASSI', 'Assigned'), ('TRAN', 'In Transit'), ('REP', 'In Repair')], max_length=100, null=True)),
                ('closed', models.CharField(choices=[('WR', 'Written Off'), ('NW', 'Not Working'), ('SL', 'Stolen/Lost'), ('RC', 'Returned to Client'), ('LC', 'Returned to Leasing Company')], max_length=100, null=True)),
                ('comments', models.TextField(null=True)),
                ('archived', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
