# Generated by Django 4.1.3 on 2023-07-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_inuseasset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='serial_num',
            field=models.TextField(editable=False, primary_key=True, serialize=False),
        ),
    ]
