# Generated by Django 4.1.3 on 2023-07-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_inventory_serial_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inuseasset',
            name='sno',
        ),
        migrations.AlterField(
            model_name='inuseasset',
            name='change_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
