# Generated by Django 4.1.3 on 2023-07-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_inventory_active_remove_inventory_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='cb_asset_id',
        ),
    ]
