# Generated by Django 4.1.3 on 2023-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_remove_inventory_cb_asset_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inuseasset',
            name='cb_asset_id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='cb_asset_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
