# Generated by Django 4.1.3 on 2023-12-17 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0008_remove_inuseasset_serial_num_inuseasset_inventory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inuseasset",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_asset",
                to="assets.inventory",
            ),
        ),
    ]
