# Generated by Django 4.1.3 on 2023-12-17 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0009_alter_inuseasset_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inuseasset",
            name="assignee_id",
        ),
        migrations.AddField(
            model_name="inuseasset",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
