# Generated by Django 4.1.3 on 2023-12-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0010_remove_inuseasset_assignee_id_inuseasset_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inuseasset",
            name="change_id",
            field=models.CharField(
                editable=False, max_length=200, primary_key=True, serialize=False
            ),
        ),
    ]
