# Generated by Django 4.1.3 on 2023-12-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0011_alter_inuseasset_change_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inuseasset",
            name="change_id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
