# Generated by Django 4.1.3 on 2023-12-26 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0012_alter_inuseasset_change_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inuseasset",
            name="name",
        ),
    ]
