# Generated by Django 4.1.3 on 2024-01-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0015_alter_inuseasset_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "assets_brands",
            },
        ),
        migrations.CreateModel(
            name="AssetModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "assets_models",
            },
        ),
        migrations.CreateModel(
            name="AssetTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "assets_types",
            },
        ),
    ]
