# Generated by Django 4.1.3 on 2024-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0016_assetbrand_assetmodels_assettypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetbrand",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="assetmodels",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="assettypes",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
