# Generated by Django 4.1.3 on 2024-01-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0017_alter_assetbrand_name_alter_assetmodels_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inuseasset",
            name="screenshot",
        ),
        migrations.AddField(
            model_name="inventory",
            name="screenshot",
            field=models.TextField(null=True),
        ),
    ]
