# Generated by Django 4.1.3 on 2023-03-16 08:58
from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType


def create_permission(apps, schema_editor):
    content_type = ContentType.objects.create(
        app_label='edit_form',
        model='change_form_related_permissions',
    )
    Permission.objects.create(
        codename='can_change_form_related_permissions',
        name='Can change form related permissions',
        content_type=content_type,
    )


def delete_permission(apps, schema_editor):
    Permission.objects.filter(codename='can_change_form_related_permissions').delete()


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_auto_20230314_0940"),
    ]

    operations = [
        migrations.RunPython(create_permission, reverse_code=delete_permission)
    ]