# Generated by Django 4.1.3 on 2024-02-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_auto_20230413_1833"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackMessageLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("delivered", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "slack_message_logs",
            },
        ),
    ]
