# Generated by Django 4.1.3 on 2024-02-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_slackmessagelogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackmessagelogs",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
    ]
